services:

  postgres:
    image: postgres:17
    container_name: pg-workflow
    environment:
      POSTGRES_DB: workflow_engine
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d workflow_engine"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: workflow-engine
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workflow_engine
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
