server.port=8082
spring.application.name=webflux-experiment

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/perfdb
spring.r2dbc.username=perfuser
spring.r2dbc.password=perfpass

logging.level.com.hogwai=INFO
