server:
  port: 8080

app:
  kafka:
    topic:
      requests: sync-requests
      results: sync-results
      replies: sync-replies
    sync-timeout-seconds: 15

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
